# Generated by Django 3.0.2 on 2020-05-14 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NigeriaState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='')),
                ('Street_Address_Line_1', models.CharField(max_length=100)),
                ('Street_Address_Line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Postal_code', models.CharField(max_length=50)),
                ('Country', models.CharField(default='Nigerian', max_length=50)),
                ('Mobile_number', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('Date_Of_Birth', models.CharField(max_length=50)),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.NigeriaState')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Begin_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('End_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Requesting_Days', models.IntegerField(default=0)),
                ('Reason', models.TextField(max_length=50)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.LeaveType')),
            ],
        ),
    ]
