# Generated by Django 3.0.2 on 2020-05-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nigeriastate',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
